# Add configuration values here, as shown below.
development:
  tmdb_api_key: "121f65c343fcbbfc19cceaf9c89e37fd"
test:
  tmdb_api_key: "121f65c343fcbbfc19cceaf9c89e37fd"
production:
  tmdb_api_key: "121f65c343fcbbfc19cceaf9c89e37fd"
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
 
